Repository AlgoGenesis/C, pull requests merged in 2024-10, with the labels that each got.

#27 #17 Add implementation of Boyer-Moore Algorithm
  String Algorithms/Boyer Moore Algorithm/Program.c
  String Algorithms/Boyer Moore Algorithm/README.md
  String Algorithms/Bucket Sort for Strings/Program.exe
Labels: new algorithm, gssoc-ext, level1

#25 Changed Best-First-Search
  Mathematical Algorithms/Backtracking Algorithms/N-Queens Problem Solver/Program.c
  Mathematical Algorithms/Backtracking Algorithms/N-Queens Problem Solver/README.md
  Mathematical Algorithms/Backtracking Algorithms/README.md
  Mathematical Algorithms/Shortest Path Algorithms/Dijkstra's algorithm.c
  Mathematical Algorithms/Shortest Path Algorithms/README.md
  Searching Algorithms/Best-First Search/Program.c
Labels: new algorithm, gssoc-ext, level3

#39 New Dynamic programming problems added
  Dynamic Programming/Longest Common Subsequence (LCS) Problem/Program.c
  Dynamic Programming/Longest Common Subsequence (LCS) Problem/README.md
  Dynamic Programming/Matrix Chain Multpilication Problem/Program.c
  Dynamic Programming/Matrix Chain Multpilication Problem/README.md
Labels: new algorithm, gssoc-ext, level2

#29 stack and queue added
  StackQueues/CircularQueue/Program.c
  StackQueues/CircularQueue/README.md
  StackQueues/DEque/Program.c
  StackQueues/DEque/README.md
  StackQueues/Queue/Program.c
  StackQueues/Queue/README.md
  StackQueues/Stack/Program.c
  StackQueues/Stack/README.md
Labels: new algorithm, gssoc-ext, level3

#33 Added Some Common Recursion Problems.
  Recursion/Factorial/Program.c
  Recursion/Factorial/README.md
  Recursion/String Palindrome/Program.c
  Recursion/String Palindrome/README.md
  Recursion/Sum of First n Natural Numbers/Program.c
  Recursion/Sum of First n Natural Numbers/README.md
  Recursion/Tower of Hanoi/Program.c
  Recursion/Tower of Hanoi/README.md
Labels: new algorithm, gssoc-ext, level2

#68 Divide and Conquer
  Divide and Conquer/Merge Sort/Program.C
  Divide and Conquer/Merge Sort/README.md
  Divide and Conquer/Quick Sort/Quick_Sort.C
  Divide and Conquer/Quick Sort/README.md
Labels: new algorithm, gssoc-ext, level1

#78 sorting algorithms added
  Sorting Algorithms/Counting Sort/Program.c
  Sorting Algorithms/Counting Sort/README.md
  Sorting Algorithms/Heap Sort/Program.c
  Sorting Algorithms/Heap Sort/Program.exe
  Sorting Algorithms/Heap Sort/README.md
  Sorting Algorithms/Insertion Sort/Program.c
  Sorting Algorithms/Insertion Sort/README.md
  Sorting Algorithms/Merge Sort/Program.c
  Sorting Algorithms/Merge Sort/Program.exe
  Sorting Algorithms/Merge Sort/README.md
  Sorting Algorithms/Quick Sort/Program.c
  Sorting Algorithms/Quick Sort/Program.exe
  Sorting Algorithms/Quick Sort/README.md
  Sorting Algorithms/Radix sort/Program.c
  Sorting Algorithms/Radix sort/README.md
Labels: algorithm update, gssoc-ext, level2

#60 Add implementation of hash XOR algorithm
  Hash Algorithms/XOR/Program.c
  Hash Algorithms/XOR/Readme.md
Labels: new algorithm, gssoc-ext, level1

#108 Addition of Singly linked list algorithms (Issue: #20)
  Linked_list/Singly_linked_list/deletion/at_the_end/program.c
  Linked_list/Singly_linked_list/deletion/at_the_end/readme.md
  Linked_list/Singly_linked_list/deletion/at_the_specific_position/program.c
  Linked_list/Singly_linked_list/deletion/at_the_specific_position/readme.md
  Linked_list/Singly_linked_list/deletion/at_the_start/program.c
  Linked_list/Singly_linked_list/deletion/at_the_start/readme.md
  Linked_list/Singly_linked_list/implementation/README.md
  Linked_list/Singly_linked_list/implementation/implementation.c
  Linked_list/Singly_linked_list/insertion/at_the_end/program.c
  Linked_list/Singly_linked_list/insertion/at_the_end/readme.md
  Linked_list/Singly_linked_list/insertion/at_the_specific_position/program.c
  Linked_list/Singly_linked_list/insertion/at_the_specific_position/readme.md
  Linked_list/Singly_linked_list/insertion/at_the_start/program.c
  Linked_list/Singly_linked_list/insertion/at_the_start/readme.md
Labels: new algorithm, gssoc-ext, level2

#101 #49 Addition of Backtracking Algos
  Backtracking Algorithms/N-Queen Algorithm/Program.c
  Backtracking Algorithms/N-Queen Algorithm/README.md
  Backtracking Algorithms/Sudoku Solver Algorithm/Program.c
  Backtracking Algorithms/Sudoku Solver Algorithm/README.md
Labels: new algorithm, gssoc-ext, level1

#105 Add implementation of Kosaraju's Algorithm
  Graph Algorithms/Kosaraju Algorithm/Program.c
  Graph Algorithms/Kosaraju Algorithm/README.md
Labels: new algorithm, gssoc-ext, level1

#163 Issue #115 solved. Added implementation of Sum of Digits Algorithm using recursion
  Recursion/Sum of Digits/Program.c
  Recursion/Sum of Digits/README.md
Labels: new algorithm, gssoc-ext, level1

#182 Added subsetsum algo
  Recursion/subset sum/Program.c
  Recursion/subset sum/README.md
Labels: new algorithm, gssoc-ext, level1

#161 Kahn's Algorithm added
  Graph Algorithms/Kahn's-Algo/Program.c
  Graph Algorithms/Kahn's-Algo/Readme.md
Labels: new algorithm, gssoc-ext, level1

#195 Added Simple DataBase Manager hash algorithm
  Hash Algorithms/SDBM/Program.c
  Hash Algorithms/SDBM/Readme.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#217 Add Longest Palindromic Substring algorithm implementation
  String Algorithms/Longest-Palindromic-Substring Algorithm/Program.c
  String Algorithms/Longest-Palindromic-Substring Algorithm/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#310 Infix To Postfix Algorithms
  Infix To Postfix/conversion/program.c
  Infix To Postfix/conversion/readme.md
  Infix To Postfix/evaluation/program.c
  Infix To Postfix/evaluation/readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#236 Added codes and README explanation files
  .gitignore
  Binary Tree Algorithms/AVL Trees Algorithms/Program.c
  Binary Tree Algorithms/AVL Trees Algorithms/README.md
  Binary Tree Algorithms/Binary Search Tree Algorithms/Program.c
  Binary Tree Algorithms/Binary Search Tree Algorithms/README.md
  Binary Tree Algorithms/Red-Black Trees Algorithms/Program.c
  Binary Tree Algorithms/Red-Black Trees Algorithms/README.md
Labels: gssoc-ext, hacktoberfest

#283 Implementation of Trie data stricture (Prefix Tree)
  Trie/ImplementTrie/ImplementTrie.c
  Trie/ImplementTrie/Readme.md
  Trie/LongestCommonPrefix/LongestCommonPrefix.c
  Trie/LongestCommonPrefix/Readme.md
  Trie/Word Break/Readme.md
  Trie/Word Break/WordBreak.c
Labels: gssoc-ext, hacktoberfest

#301 #137 Added the mentioned 5 algorithms under String Algorithms
  String Algorithms/Apostolico–Giancarlo Algorithm/Program.c
  String Algorithms/Apostolico–Giancarlo Algorithm/README.md
  String Algorithms/BNDM Algorithm/Program.c
  String Algorithms/BNDM Algorithm/README.md
  String Algorithms/Bitap Algorithm/Program.c
  String Algorithms/Bitap Algorithm/README.md
  String Algorithms/Commentz-Walter Algorithm/Program.c
  String Algorithms/Commentz-Walter Algorithm/README.md
  String Algorithms/Shift-Or Algorithm/Program.c
  String Algorithms/Shift-Or Algorithm/README.md
Labels: gssoc-ext, hacktoberfest

#309 Added Fibonacci Search
  Searching Algorithms/Fibonacci Search/Program.c
  Searching Algorithms/Fibonacci Search/README.md
  Sorting Algorithms/Selection Sort/Program.c
  Sorting Algorithms/Selection Sort/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#312 Add Core Operations for Doubly Linked List
  Linked_list/Doubly_linked_list/deletion/at_the_end/program.c
  Linked_list/Doubly_linked_list/deletion/at_the_end/readme.md
  Linked_list/Doubly_linked_list/deletion/at_the_specific_position/program.c
  Linked_list/Doubly_linked_list/deletion/at_the_specific_position/readme.md
  Linked_list/Doubly_linked_list/deletion/at_the_start/program.c
  Linked_list/Doubly_linked_list/deletion/at_the_start/readme.md
  Linked_list/Doubly_linked_list/implementation/README.md
  Linked_list/Doubly_linked_list/implementation/implementation.c
  Linked_list/Doubly_linked_list/insertion/at_the_end/program.c
  Linked_list/Doubly_linked_list/insertion/at_the_end/readme.md
  Linked_list/Doubly_linked_list/insertion/at_the_specific_position/program.c
  Linked_list/Doubly_linked_list/insertion/at_the_specific_position/readme.md
  Linked_list/Doubly_linked_list/insertion/at_the_start/program.c
  Linked_list/Doubly_linked_list/insertion/at_the_start/readme.md
Labels: question, gssoc-ext, hacktoberfest

#319 Generate Subsets
  Recursion/Generate Subsets/Program.c
  Recursion/Generate Subsets/Readme.md
Labels: gssoc-ext, hacktoberfest

#326 Added Maze Solving Algorithm
  Backtracking Algorithms/Maze Solving/README.md
  Backtracking Algorithms/Maze Solving/program.c
Labels: gssoc-ext, hacktoberfest

#204 Added 32-bit CRC hash
  Hash Algorithms/CRC/Program.c
  Hash Algorithms/CRC/Readme.md
Labels: gssoc-ext, hacktoberfest

#338 # Strassen's Algorithm for Matrix Multiplication
  Divide and Conquer/Strassen's Algorithm for Matrix Multiplication/README.md
  Divide and Conquer/Strassen's Algorithm for Matrix Multiplication/program.c
Labels: gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#348 [NEW ALGORITHM] Implemented Union-Find Algorithm for Connectivity Check #345
  Miscellaneous Algorithms/Union-Find for Connectivity/Program.c
  Miscellaneous Algorithms/Union-Find for Connectivity/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#353 Addition of 4 Backtracking Algorithms | Issue #176
  Backtracking Algorithms/Hamiltonian Path Problem/Program.c
  Backtracking Algorithms/Hamiltonian Path Problem/README.md
  Backtracking Algorithms/Permutations and Combinations/Program.c
  Backtracking Algorithms/Permutations and Combinations/README.md
  Backtracking Algorithms/Rat in a Maze Problem/Program.c
  Backtracking Algorithms/Rat in a Maze Problem/README.md
  Backtracking Algorithms/Subset Sum Problem/Program.c
  Backtracking Algorithms/Subset Sum Problem/README.md
Labels: gssoc-ext, hacktoberfest

#355 Addition of TSP | Issue #174
  Graph Algorithms/Traveling Salesman Problem (TSP)/Program.c
  Graph Algorithms/Traveling Salesman Problem (TSP)/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#361 Gnome sort created
  Sorting Algorithms/GnomeSort/README.md
  Sorting Algorithms/GnomeSort/program.c
Labels: gssoc-ext, hacktoberfest

#389 Add A* (A-Star) Algorithm for Pathfinding in C
  Graph Algorithms/A-Star/Program.c
  Graph Algorithms/A-Star/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#409 Added M - Coloring Problem Algorithm
  Backtracking Algorithms/M - Coloring Problem Algorithm/Program.c
  Backtracking Algorithms/M - Coloring Problem Algorithm/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#399 Added the Kadane's Algorithm
  Kadan'Algorithm/Kadan_Algorithm.c
  Kadan'Algorithm/README.md
Labels: new algorithm, gssoc-ext, level3, hacktoberfest-accepted

#446 added 2sum, 3sum and 4sum algos
  Hash/two sum/README.md
  Hash/two sum/program.c
  two pointer/3 sum/README.md
  two pointer/3 sum/program.c
  two pointer/4 sum/README.md
  two pointer/4 sum/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#448 Added Shell Sort and Random Quick Sort Algorithms #438
  Sorting Algorithms/Randomized Quick Sort/Program.c
  Sorting Algorithms/Randomized Quick Sort/README.md
  Sorting Algorithms/Shell Sort/Program.c
  Sorting Algorithms/Shell Sort/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#478 Added the circular linked list
  Linked_list/Circular_Linked_list/deletion/at_a_specific_position/program.c
  Linked_list/Circular_Linked_list/deletion/at_a_specific_position/readme.md
  Linked_list/Circular_Linked_list/deletion/at_the_end/program.c
  Linked_list/Circular_Linked_list/deletion/at_the_end/readme.md
  Linked_list/Circular_Linked_list/deletion/at_the_start/program.c
  Linked_list/Circular_Linked_list/deletion/at_the_start/readme.md
  Linked_list/Circular_Linked_list/implementation/program.c
  Linked_list/Circular_Linked_list/implementation/readme.md
  Linked_list/Circular_Linked_list/insertion/at_the_end/program.c
  Linked_list/Circular_Linked_list/insertion/at_the_end/readme.md
  Linked_list/Circular_Linked_list/insertion/at_the_specific_position/program.c
  Linked_list/Circular_Linked_list/insertion/at_the_specific_position/readme.md
  Linked_list/Circular_Linked_list/insertion/at_the_start/program.c
  Linked_list/Circular_Linked_list/insertion/at_the_start/readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#491 #490 [Solved] Inserted Cycle Sort Algorithm
  Sorting Algorithms/Cycle Sort/Program.c
  Sorting Algorithms/Cycle Sort/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#509 Added heap insertion and deletion program
  Heap insert and delete/README.md
  Heap insert and delete/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#511 Added the Job Scheduling with deadline program inside the greedy algorithm folder
  Greedy Algorithms/Job Scheduling with Deadline/README.md
  Greedy Algorithms/Job Scheduling with Deadline/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#533 backtracking algo - Knight's Tour Problem
  Backtracking Algorithms/Knight's Tour Problem/README.md
  Backtracking Algorithms/Knight's Tour Problem/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#554 Added Polygon Area Calculation
  Mathematical Algorithms/Polygon Area Calculation/Program.c
  Mathematical Algorithms/Polygon Area Calculation/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#501 Aggressive Cows Problem
  Trie/Aggressive Cows/Program.c
  Trie/Aggressive Cows/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#580 Added Mathematical Algorithms
  Mathematical Algorithms/Chinese Remainder Theorem/README.md
  Mathematical Algorithms/Chinese Remainder Theorem/program.c
  Mathematical Algorithms/Least Common Multiple (LCM)/README.md
  Mathematical Algorithms/Least Common Multiple (LCM)/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#659 Flood Fill Algorithm Via Recusrrsion
  Recursion/FloodFillAlgorithm/FloodFillAlgo.c
  Recursion/FloodFillAlgorithm/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#700 Added Pythagorus Algorithm
  Mathematical Algorithms/Pythagorus Algorithm/README.md
  Mathematical Algorithms/Pythagorus Algorithm/pythagorus.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#855 [NEW ALGORITHM] Vigenère cipher algorithm
  Cipher/Vigenère/README.md
  Cipher/Vigenère/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#938 added 180 degree rotation code and explanation
  2D Arrays/RotateTheMatrixBY180/clockwise.c
  2D Arrays/RotateTheMatrixBY180/readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#897 Added dutch national flag algo, sjf scheduling and lru page replacement algorithms
  Miscellaneous Algorithms/Dutch-National-Flag/Program.c
  Miscellaneous Algorithms/Dutch-National-Flag/Readme.md
  Miscellaneous Algorithms/LRU-page replacement/Program.c
  Miscellaneous Algorithms/LRU-page replacement/Readme.md
  Miscellaneous Algorithms/SJF Scheduling/Program.c
  Miscellaneous Algorithms/SJF Scheduling/Readme.md
Labels: duplicate

#1185 sleep sort added
  Sorting Algorithms/Sleep Sort/Program.c
  Sorting Algorithms/Sleep Sort/README.md
Labels: new algorithm, hacktoberfest-accepted

#1186 Kleinberg-Tardos algorithm added
  Graph Algorithms/Kleinberg-Tardos Algorithm/Program.c
  Graph Algorithms/Kleinberg-Tardos Algorithm/README.md
Labels: new algorithm, hacktoberfest-accepted

#1142 Added Skyline Problem
  Divide and Conquer/Skyline Problem/Program.c
  Divide and Conquer/Skyline Problem/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1305 Added the code and readme file for "Minimum Machines for Maximum Output"
  Optimization Algorithms/Binary Greedy Algorithm/Program.C
  Optimization Algorithms/Binary Greedy Algorithm/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1351 Minimum Heap Implementation in C
  Heaps/Minimum Heap/README.md
  Heaps/Minimum Heap/min-heap.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1373 Added Set Matrix Zero
  2D Arrays/SetMatrixZero/Program.c
  2D Arrays/SetMatrixZero/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1375 Added the algorithm
  Backtracking Algorithms/Leaf Similar Tree/Program_leaf.c
  Backtracking Algorithms/Leaf Similar Tree/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1445 Made the modification
  Trie/Aggressive Cows Problem/ProgramAgg.c
  Trie/Aggressive Cows Problem/Readme.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1511 Added the program of Symmetric Tree
  Binary Tree Algorithms/Symmetric Tree/README.md
  Binary Tree Algorithms/Symmetric Tree/program.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1516 #1436 Added Smith-Waterman Algorithm
  String Algorithms/Smith-Waterman Algorithm/Program.c
  String Algorithms/Smith-Waterman Algorithm/README.md
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted

#1520 Implement a Function to Merge Two Binary Search Trees (BSTs) #1441
  Binary Tree Algorithms/Merge two BSTs/README.md
  Binary Tree Algorithms/Merge two BSTs/mergeBSTs.c
Labels: new algorithm, gssoc-ext, level1, hacktoberfest-accepted
